test-1
MarkiianSanotskyi/my-app3 pull request #1
Opened 2019-05-02 00:39 UTC by MarkiianSanotskyi

2019-05-02 06:21 UTC, bassment requested changes

2019-05-02 06:21 UTC, bassment commented on src/components/pages/Home/Home.js
> +const Styles = styled.div`
вместо `Styles` назви `Container` как ты в `FooterBar` сделал

2019-05-02 06:21 UTC, bassment commented on src/components/pages/Home/Home.js
> +  .container {
Клас можешь здесь убрать оставь просто стили

2019-05-02 06:21 UTC, bassment commented on src/components/pages/Home/Home.js
> +    <Styles>
удаляй

2019-05-02 06:21 UTC, bassment commented on src/components/pages/Home/Home.js
> +      <Container className="container">
уберай клас

2019-05-02 06:21 UTC, bassment commented on src/components/pages/Home/Home.js
> +      li {
что бы засилить `li` i `ul` создай константу( `const StyledLi = styled.li....` ) так же как с `Container` как я выше просил

2019-05-02 06:21 UTC, bassment commented on src/components/pages/Home/Home.js
> +const Styles = styled.div`
И выдели стили в отдельный файл и импортни тут

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/CopyrightBar/CopyrightBar.js
> +const Styles = styled.div`
тоже самое что в хоуме я просил, в отдельный файл и констату для `p`

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/CopyrightBar/CopyrightBar.js
> +const Styles = styled.div`
можешь назвать `StyledP`

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/SearchBar/SearchBar.js
> +        </form>{" "}
такого лучше не делать `{" "}`

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/SelectLangBar/SelectLangBar.js
> +const Styles = styled.div`
тоже самое что просил выше

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/NavigationBar/NavigationBar.js
> +const Styles = styled.div`
тоже самое что просил выше. ты норм сделал в `FooterBar` Сделай так же

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/FooterPayment/FooterPayment.js
> +      <ul className="NavigationList">
класы не нужны если ты не пишешь тесты

2019-05-02 06:21 UTC, bassment commented on src/components/shared/Layout/FooterNavigationBar/FooterNavigationBar.js
> +const Styles = styled.div`
тоже самое

2019-05-02 16:50 UTC, bassment commented on package.json
> +    "eslint-config-airbnb": "^17.1.0",
зачем это? оно должно работать без этого

2019-05-02 16:50 UTC, bassment commented on package.json
> +    "eslint": "^5.16.0",
удали и поставь eslint глобально лучше - `npm i -g eslint`

2019-05-02 17:31 UTC, MarkiianSanotskyi commented on src/components/pages/Home/Home.js
> +    <Styles>
А как тут понять о чем ты написал?

2019-05-02 17:33 UTC, MarkiianSanotskyi commented on src/components/shared/Layout/SearchBar/SearchBar.js
> +        </form>{" "}
Это у меня какая то из Либ Делает эту херь, незнаю какая  точно и в какие моменты. Было бы хорошо если бы ты обьяснил что это? или ссылочку

2019-05-02 19:40 UTC, bassment commented on src/components/pages/Home/Home.js
> +    <Styles>
можешь удалить обертку <Styles> она не нужна. Создавай компоненты со стилями  напрямую типа - const StyledLi = styled.li`color: red;`

2019-05-02 20:08 UTC, MarkiianSanotskyi commented on src/components/pages/Home/Home.js
> +const Styles = styled.div`
Так Антон глянь

2019-05-03 06:42 UTC, bassment commented on src/components/shared/Layout/SearchBar/SearchBar.js
> +        </form>{" "}
походу отступ. но удаляй

2019-05-07 19:34 UTC, merged